version: "3.8"

services:
  synophoto-thumbnail-generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: gwlee/synophoto-thumbnail-generator
    volumes:
      - ./data:/app/data