version: "3.8"

services:
  synophoto-thumbnail-generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: gwlee/synophoto-thumbnail-generator
    environment:
      - MAX_CONCURRENT=5
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs